export const mockUsers = [
    {
        id: "1",
        name: "Олександр Петренко",
        email: "alex.petrenko@example.com",
        role: "admin",
        registrationDate: "2024-01-15",
        lastLogin: "2024-03-20",
        ordersCount: 12,
        avatar: "/placeholder.svg?height=40&width=40",
    },
    {
        id: "2",
        name: "Марія Іваненко",
        email: "maria.ivanenko@example.com",
        role: "customer",
        registrationDate: "2024-02-10",
        lastLogin: "2024-03-19",
        ordersCount: 5,
        avatar: "/placeholder.svg?height=40&width=40",
    },
    {
        id: "3",
        name: "Дмитро Коваленко",
        email: "dmytro.kovalenko@example.com",
        role: "customer",
        registrationDate: "2024-01-20",
        lastLogin: "2024-03-10",
        ordersCount: 0,
        avatar: "/placeholder.svg?height=40&width=40",
    },
    {
        id: "4",
        name: "Анна Шевченко",
        email: "anna.shevchenko@example.com",
        role: "moderator",
        registrationDate: "2024-03-01",
        lastLogin: "2024-03-20",
        ordersCount: 8,
        avatar: "/placeholder.svg?height=40&width=40",
    },
]
