export const mockOrders = [
    {
        id: "ORD-001",
        customerName: "Олександр Петренко",
        customerEmail: "alex.petrenko@example.com",
        date: "2024-03-20",
        status: "pending",
        total: 1250.0,
        items: 3,
        paymentMethod: "card",
        shippingAddress: "вул. Хрещатик, 1, Київ",
        products: [
            { name: "iPhone 15 Pro", quantity: 1, price: 1000.0 },
            { name: "Чохол для iPhone", quantity: 1, price: 150.0 },
            { name: "Захисне скло", quantity: 1, price: 100.0 },
        ],
    },
    {
        id: "ORD-002",
        customerName: "Марія Іваненко",
        customerEmail: "maria.ivanenko@example.com",
        date: "2024-03-19",
        status: "processing",
        total: 750.5,
        items: 2,
        paymentMethod: "cash",
        shippingAddress: "вул. Шевченка, 15, Львів",
        products: [
            { name: "Samsung Galaxy S24", quantity: 1, price: 650.5 },
            { name: "Навушники", quantity: 1, price: 100.0 },
        ],
    },
    {
        id: "ORD-003",
        customerName: "Дмитро Коваленко",
        customerEmail: "dmytro.kovalenko@example.com",
        date: "2024-03-18",
        status: "shipped",
        total: 2100.0,
        items: 1,
        paymentMethod: "card",
        shippingAddress: "вул. Грушевського, 5, Одеса",
        products: [{ name: "MacBook Air M2", quantity: 1, price: 2100.0 }],
    },
    {
        id: "ORD-004",
        customerName: "Анна Шевченко",
        customerEmail: "anna.shevchenko@example.com",
        date: "2024-03-17",
        status: "delivered",
        total: 450.0,
        items: 4,
        paymentMethod: "card",
        shippingAddress: "вул. Франка, 20, Харків",
        products: [
            { name: "Футболка Nike", quantity: 2, price: 150.0 },
            { name: "Кросівки Adidas", quantity: 1, price: 300.0 },
        ],
    },
    {
        id: "ORD-005",
        customerName: "Петро Мельник",
        customerEmail: "petro.melnyk@example.com",
        date: "2024-03-16",
        status: "cancelled",
        total: 320.0,
        items: 1,
        paymentMethod: "card",
        shippingAddress: "вул. Лесі Українки, 8, Дніпро",
        products: [{ name: "Планшет Samsung", quantity: 1, price: 320.0 }],
    },
]
